// src/pages/employee/MyPayroll.jsx
import { useEffect, useState } from 'react';
import { toast } from 'react-toastify';
import { FiDollarSign, FiTrendingUp, FiTrendingDown } from 'react-icons/fi';
import Layout from '../../components/common/Layout';
import PageHeader from '../../components/common/PageHeader';
import EmptyState from '../../components/common/EmptyState';
import Loader from '../../components/common/Loader';
import payrollService from '../../services/payrollService';
import { useAuth } from '../../context/AuthContext';
import { formatCurrency, getStatusBadge } from '../../utils/helpers';
import { FaRupeeSign } from 'react-icons/fa';

const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];

const MyPayroll = () => {
  const { user } = useAuth();
  const [payrolls, setPayrolls] = useState([]);
  const [selected, setSelected] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (user?.employeeId) fetchPayrolls();
  }, [user]);

  const fetchPayrolls = async () => {
    try {
      const res = await payrollService.getByEmployee(user.employeeId);
      const data = res.data.data || [];
      setPayrolls(data);
      if (data.length > 0) setSelected(data[0]);
    } catch {
      toast.error('Failed to load payroll');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Layout>
      <PageHeader
        title="My Payroll"
        subtitle="View your salary and payslip history"
      />

      {loading ? (
        <Loader fullScreen={false} />
      ) : payrolls.length === 0 ? (
        <div className="card">
          <EmptyState
            icon={FaRupeeSign}
            title="No Payroll Records"
            description="Your payslips will appear here once generated by admin"
          />
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Payslip List */}
          <div className="lg:col-span-1">
            <div className="card p-0 overflow-hidden">
              <div className="px-4 py-3 bg-gray-50 border-b border-gray-200">
                <h3 className="font-semibold text-gray-700 text-sm">
                  Payslip History
                </h3>
              </div>
              <div className="divide-y divide-gray-100 max-h-96 
                              overflow-y-auto">
                {payrolls.map((p) => (
                  <button
                    key={p.id}
                    onClick={() => setSelected(p)}
                    className={`w-full px-4 py-3 text-left hover:bg-gray-50 
                                transition-colors
                      ${selected?.id === p.id ?
                        'bg-primary-50 border-l-4 border-primary-600' :
                        ''}`}
                  >
                    <p className="font-medium text-sm text-gray-800">
                      {MONTHS[p.month - 1]} {p.year}
                    </p>
                    <div className="flex items-center justify-between mt-1">
                      <span className="text-xs text-gray-500">
                        Net: {formatCurrency(p.netSalary)}
                      </span>
                      <span className={getStatusBadge(p.status)}>
                        {p.status}
                      </span>
                    </div>
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Payslip Detail */}
          {selected && (
            <div className="lg:col-span-2">
              <div className="card">
                {/* Header */}
                <div className="flex items-center justify-between 
                                pb-4 mb-4 border-b border-gray-200">
                  <div>
                    <h2 className="text-xl font-bold text-gray-800">
                      Payslip - {MONTHS[selected.month - 1]} {selected.year}
                    </h2>
                    <p className="text-gray-500 text-sm mt-0.5">
                      {selected.employeeName} • {selected.employeeCode}
                    </p>
                  </div>
                  <span className={getStatusBadge(selected.status)}>
                    {selected.status}
                  </span>
                </div>

                {/* Attendance */}
                <div className="grid grid-cols-2 gap-4 mb-6 
                                p-4 bg-gray-50 rounded-xl">
                  <div className="text-center">
                    <p className="text-2xl font-bold text-gray-800">
                      {selected.workingDays}
                    </p>
                    <p className="text-xs text-gray-500">Working Days</p>
                  </div>
                  <div className="text-center">
                    <p className="text-2xl font-bold text-green-600">
                      {selected.presentDays}
                    </p>
                    <p className="text-xs text-gray-500">Present Days</p>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {/* Earnings */}
                  <div>
                    <div className="flex items-center gap-2 mb-3">
                      <FiTrendingUp className="text-green-600" />
                      <h3 className="font-semibold text-gray-700">
                        Earnings
                      </h3>
                    </div>
                    <div className="space-y-2">
                      {[
                        ['Basic Salary', selected.basicSalary],
                        ['HRA', selected.hra],
                        ['Transport', selected.transportAllowance],
                        ['Medical', selected.medicalAllowance],
                        ['Other', selected.otherAllowances],
                      ].map(([label, value]) => (
                        <div key={label}
                             className="flex justify-between text-sm">
                          <span className="text-gray-500">{label}</span>
                          <span className="font-medium text-gray-700">
                            {formatCurrency(value)}
                          </span>
                        </div>
                      ))}
                      <div className="flex justify-between text-sm 
                                      border-t border-gray-200 pt-2 mt-2">
                        <span className="font-semibold text-gray-700">
                          Gross Salary
                        </span>
                        <span className="font-bold text-green-600">
                          {formatCurrency(selected.grossSalary)}
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* Deductions */}
                  <div>
                    <div className="flex items-center gap-2 mb-3">
                      <FiTrendingDown className="text-red-500" />
                      <h3 className="font-semibold text-gray-700">
                        Deductions
                      </h3>
                    </div>
                    <div className="space-y-2">
                      {[
                        ['PF', selected.pfDeduction],
                        ['Tax', selected.taxDeduction],
                        ['Other', selected.otherDeductions],
                      ].map(([label, value]) => (
                        <div key={label}
                             className="flex justify-between text-sm">
                          <span className="text-gray-500">{label}</span>
                          <span className="font-medium text-red-500">
                            -{formatCurrency(value)}
                          </span>
                        </div>
                      ))}
                      <div className="flex justify-between text-sm 
                                      border-t border-gray-200 pt-2 mt-2">
                        <span className="font-semibold text-gray-700">
                          Total Deductions
                        </span>
                        <span className="font-bold text-red-500">
                          -{formatCurrency(selected.totalDeductions)}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Net Salary */}
                <div className="mt-6 p-4 bg-gradient-to-r from-green-50 
                                to-emerald-50 rounded-xl border 
                                border-green-200">
                  <div className="flex justify-between items-center">
                    <span className="font-bold text-gray-700 text-lg">
                      💰 Net Salary
                    </span>
                    <span className="font-bold text-green-600 text-2xl">
                      {formatCurrency(selected.netSalary)}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      )}
    </Layout>
  );
};
export default MyPayroll;